### ISSUE TITLE
Font color is changed when Dark theme is enabled

### ISSUE THREAD

**Issue by NadjibSb** [YunsGeek/Quraan-Player#3]
![Screenshot_20220128-190435](https://user-images.githubusercontent.com/25468825/151599234-8fc0d587-7cec-4696-b459-f8db6220bc69.png)

**Comment by YunsGeek** [comment]
hi , 
thank you for your report , 
i have noticied that in a Xiaomi phone , this problem occures because the app does not have its own dark mode so the system force it to use its default colors .
we will fix this issue in next version inshaa allah .
thank you again  , have a nice day

**Comment by NadjibSb** [comment]
I may contribute to the project int he upcoming days. I will try to fix the issue.
Good work.

**Comment by YunsGeek** [comment]
thank you sir 🌹
